name: .NET Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest 
    
    env:
      Solution_Name: RBTools.sln
      Working_Directory: RBTools
      dotNET_Version: '4.8.x'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet Packages
      working-directory: ${{ env.Working_Directory }}
      run: nuget restore ${{ env.Solution_Name }}

    - name: Build the application
      working-directory: ${{ env.Working_Directory }}
      run: msbuild ${{ env.Solution_Name }} /t:Build /p:Configuration=Release
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Execute unit tests
      run: dotnet test
      working-directory: ${{ env.Working_Directory }}
