name: .NET Desktop

on: [ workflow_dispatch ]
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest 
    
    env:
      Solution_Name: RBTools.sln
      Working_Directory: RBTools
      dotNET_Version: '4.8.x'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet Packages
      run: nuget restore ${{ env.Solution_Name }}

    # Execute all unit tests in the solution
#     - name: Execute unit tests
#       run: dotnet test
#       working-directory: ${{ env.Working_Directory }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: msbuild ${{ env.Solution_Name }} /t:Build /p:Configuration=Release
      working-directory: ${{ env.Working_Directory }}
      env:
        Configuration: ${{ matrix.configuration }}
