name: .NET Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest 
    
    env:
      Solution_Name: RBTools.sln
      Working_Directory: RBTools
      NETCORE_VERSION: '5.0.101'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
      
    - name: Restore NuGet Packages
      working-directory: ${{ env.Working_Directory }}
      run: dotnet restore

    - name: Build the application
      working-directory: ${{ env.Working_Directory }}
      run: dotnet build
        
    - name: Execute unit tests
      run: dotnet test
      working-directory: ${{ env.Working_Directory }}
